HTML="""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Nano AI</title><style>
body{margin:0;background:#080b12;color:#edf2ff;font:15px system-ui}.app{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.side{padding:14px;border-right:1px solid #202a3c;background:#0c111b}.brand{font-size:22px;font-weight:800;margin:8px 0 16px}.new{width:100%;margin-bottom:10px}nav button,.conv button{display:block;width:100%;margin:4px 0;padding:9px;text-align:left;border:1px solid transparent;border-radius:9px;background:transparent;color:#aab6cf;cursor:pointer}nav button.active,nav button:hover,.conv button.active{background:#151e2e;color:#fff}.conv{border-top:1px solid #202a3c;margin-top:12px;padding-top:8px;max-height:35vh;overflow:auto}.conv button{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.main{padding:22px;max-width:1100px;width:calc(100% - 44px);margin:auto}.page{display:none}.page.active{display:block}.panel{background:#111725;border:1px solid #26324a;border-radius:18px;padding:18px}.chat{height:55vh;overflow:auto}.msg{max-width:82%;padding:12px;margin:9px 0;border-radius:13px;white-space:pre-wrap}.user{margin-left:auto;background:#1b3155}.assistant{background:#161e2e}.composer{display:flex;gap:8px;flex-wrap:wrap}.composer textarea{flex:1;min-width:220px;background:#0b1019;color:#fff;border:1px solid #2a3850;border-radius:10px;padding:12px}.btn{padding:10px 14px;border-radius:10px;border:1px solid #33445f;background:#18243a;color:#fff;cursor:pointer}.btn.recording{outline:2px solid #ff6b6b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.item{padding:12px;border:1px solid #27344a;border-radius:12px;background:#0d131e}.hint{color:#8491aa;font-size:12px}.danger{float:right}.small{font-size:12px;color:#8491aa}@media(max-width:700px){.app{grid-template-columns:1fr}.side{border-right:0;border-bottom:1px solid #202a3c}.main{width:auto}.conv{max-height:180px}}
</style></head><body><div class='app'><aside class='side'><div class='brand'>◉ Nano AI</div><button class='btn new' id='newConv'>＋ New chat</button><div id='convs' class='conv'></div><nav><button data-p='talk' class='active'>Talk</button><button data-p='memory'>Memory</button><button data-p='learning'>Learning</button><button data-p='skills'>Skills</button><button data-p='knowledge'>Knowledge</button><button data-p='model'>Model</button><button data-p='settings'>Settings</button><button data-p='system'>System</button></nav></aside><main class='main'>
<section id='talk' class='page active'><div class='panel'><h2>Talk <small id='status'></small></h2><div id='chat' class='chat'></div><div class='composer'><textarea id='input' placeholder='Talk to Nano...'></textarea><button class='btn' id='send'>Send</button><button class='btn' id='mic'>🎙 Start recording</button><label class='btn'>WAV file <input id='wav' type='file' accept='.wav,audio/wav' hidden></label></div><div><span id='voiceStatus' class='hint'>Checking local Vosk + Piper...</span></div><audio id='player' controls hidden></audio></div></section>
<section id='memory' class='page'><div class='panel'><h2>Memory</h2><input id='mq' placeholder='Search memory' style='width:100%;box-sizing:border-box;padding:11px;background:#0b1019;color:white;border:1px solid #2a3850;border-radius:9px'><div id='ml' class='grid'></div></div></section>
<section id='learning' class='page'><div class='panel'><h2>Learning</h2><p>Explicit learning only. Model weights are never silently changed.</p><div id='ll' class='grid'></div></div></section>
<section id='skills' class='page'><div class='panel'><h2>Skills</h2><div id='sl' class='grid'></div><h3>Skill proposals</h3><div id='spl' class='grid'></div></div></section>
<section id='knowledge' class='page'><div class='panel'><h2>Knowledge</h2><textarea id='kt' style='width:100%;height:180px;box-sizing:border-box;background:#0b1019;color:white;padding:11px'></textarea><p><button class='btn' onclick='ingest()'>Import locally</button></p><div id='kl' class='grid'></div></div></section>
<section id='model' class='page'><div class='panel'><h2>Model</h2><pre id='mi'></pre></div></section>
<section id='settings' class='page'><div class='panel'><h2>Settings</h2><div id='setl' class='grid'></div></div></section>
<section id='system' class='page'><div class='panel'><h2>System</h2><pre id='si'></pre></div></section>
</main></div><script>
const $=x=>document.getElementById(x),api=(u,o)=>fetch(u,o).then(async r=>{if(!r.ok)throw Error(await r.text());return r.json()});let cid=1,recording=false,ctx=null,proc=null,stream=null,chunks=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function add(role,t){let d=document.createElement('div');d.className='msg '+role;d.textContent=t;$('chat').appendChild(d);$('chat').scrollTop=$('chat').scrollHeight}
async function loadConvs(){let a=await api('/api/conversations');if(!a.length)return; if(!a.some(x=>x.id===cid))cid=a[0].id;$('convs').innerHTML=a.map(x=>'<button class="'+(x.id===cid?'active':'')+'" data-id="'+x.id+'">'+esc(x.title)+'</button>').join('');$('convs').querySelectorAll('button').forEach(b=>b.onclick=()=>selectConv(Number(b.dataset.id)));}
async function selectConv(id){cid=id;$('chat').innerHTML='';let a=await api('/api/conversations/'+id+'/messages');a.forEach(x=>add(x.role,x.content));await loadConvs()}
async function newConv(){let x=await api('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'New conversation'})});cid=x.id;$('chat').innerHTML='';await loadConvs();$('input').focus()}
$('newConv').onclick=newConv;
async function send(){let t=$('input').value.trim();if(!t)return;$('input').value='';add('user',t);try{let a=(await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:cid,message:t})})).answer;add('assistant',a);speak(a);await loadConvs()}catch(e){add('assistant','Error: '+e.message)}}
$('send').onclick=send;$('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}
async function speak(t){try{let r=await fetch('/api/voice/tts?text='+encodeURIComponent(t));if(!r.ok)throw Error(await r.text());let b=await r.blob(),u=URL.createObjectURL(b);$('player').src=u;$('player').hidden=false;$('player').play().catch(()=>{});$('voiceStatus').textContent='Piper: speaking locally.'}catch(e){$('voiceStatus').textContent='Piper unavailable: '+e.message}}
function wavBlob(parts,rate){let n=parts.reduce((a,b)=>a+b.length,0),pcm=new Float32Array(n),o=0;parts.forEach(x=>{pcm.set(x,o);o+=x.length});let b=new ArrayBuffer(44+n*2),v=new DataView(b),u=(p,s)=>{for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i))},w=(p,x)=>v.setUint32(p,x,true),h=(p,x)=>v.setUint16(p,x,true);u(0,'RIFF');w(4,36+n*2);u(8,'WAVE');u(12,'fmt ');w(16,16);h(20,1);h(22,1);w(24,rate);w(28,rate*2);h(32,2);h(34,16);u(36,'data');w(40,n*2);for(let i=0,p=44;i<n;i++,p+=2){let x=Math.max(-1,Math.min(1,pcm[i]));v.setInt16(p,x<0?x*32768:x*32767,true)}return new Blob([v],{type:'audio/wav'})}
async function startMic(){if(!navigator.mediaDevices?.getUserMedia){$('voiceStatus').textContent='Microphone API unavailable; use WAV upload.';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});ctx=new (window.AudioContext||window.webkitAudioContext)();let src=ctx.createMediaStreamSource(stream);proc=ctx.createScriptProcessor(4096,1,1);chunks=[];proc.onaudioprocess=e=>chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)));src.connect(proc);proc.connect(ctx.destination);recording=true;$('mic').textContent='⏹ Stop & transcribe';$('mic').classList.add('recording');$('voiceStatus').textContent='Recording locally...'}catch(e){$('voiceStatus').textContent='Microphone error: '+e.message}}
async function stopMic(){try{proc.disconnect();stream.getTracks().forEach(t=>t.stop());let blob=wavBlob(chunks,ctx.sampleRate);await ctx.close();proc=ctx=stream=null;recording=false;$('mic').textContent='🎙 Start recording';$('mic').classList.remove('recording');$('voiceStatus').textContent='Sending audio to local Vosk...';let f=new FormData();f.append('file',blob,'microphone.wav');let r=await api('/api/voice/stt',{method:'POST',body:f});$('input').value=r.text||'';$('voiceStatus').textContent=r.text?'Vosk: transcription ready. Press Send.':'Vosk: no speech detected.'}catch(e){recording=false;$('mic').textContent='🎙 Start recording';$('mic').classList.remove('recording');$('voiceStatus').textContent='Voice error: '+e.message}}
$('mic').onclick=()=>recording?stopMic():startMic();
$('wav').onchange=e=>{let f=e.target.files[0];if(!f)return;$('voiceStatus').textContent='Vosk: transcribing locally...';let x=new FormData();x.append('file',f);api('/api/voice/stt',{method:'POST',body:x}).then(r=>{$('input').value=r.text||'';$('voiceStatus').textContent=r.text?'Vosk: transcription ready. Press Send.':'Vosk: no speech detected.'}).catch(e=>$('voiceStatus').textContent='Vosk error: '+e.message)}
async function loadMemory(){let q=$('mq').value||'';let a=await api('/api/memories?q='+encodeURIComponent(q));$('ml').innerHTML=a.map(x=>'<div class=item><button class="btn danger" data-del="'+x.id+'">Forget</button><b>'+esc(x.kind)+'</b><p>'+esc(x.content)+'</p><span class=small>confidence '+Number(x.confidence).toFixed(2)+' • '+esc(x.source)+'</span></div>').join('');$('ml').querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await api('/api/memories/'+b.dataset.del,{method:'DELETE'});loadMemory()})}
$('mq').oninput=loadMemory;
async function loadSkills(){let a=await api('/api/skills');$('sl').innerHTML=a.map(x=>'<div class=item><button class="btn danger" data-skill="'+esc(x.name)+'">'+(x.enabled?'Disable':'Enable')+'</button><b>'+esc(x.name)+'</b><p>'+esc(x.description)+'</p><span class=small>v'+x.version+'</span></div>').join('');$('sl').querySelectorAll('[data-skill]').forEach(b=>b.onclick=async()=>{let name=b.dataset.skill,all=a.find(x=>x.name===name);await api('/api/skills/'+encodeURIComponent(name)+'/enabled?enabled='+(all.enabled?false:true),{method:'POST'});loadSkills()})}
async function loadLearning(){let a=await api('/api/learning/events');$('ll').innerHTML=a.map(x=>'<div class=item><b>'+esc(x.event_type)+'</b><p>'+esc(x.input_text)+'</p><span class=small>'+esc(x.result||'')+'</span></div>').join('')}
function renderKnowledge(a){$('kl').innerHTML=a.map(x=>'<div class=item><b>'+esc(x.kind)+'</b><p>'+esc(x.content)+'</p><span class=small>'+esc(x.source)+'</span></div>').join('')}
async function load(p){if(p==='memory')loadMemory();if(p==='learning')loadLearning();if(p==='skills'){loadSkills();loadSkillProposals();}if(p==='knowledge')renderKnowledge(await api('/api/knowledge'));if(p==='model')$('mi').textContent=JSON.stringify(await api('/api/model'),null,2);if(p==='system')$('si').textContent=JSON.stringify(await api('/api/system'),null,2);if(p==='settings'){let s=await api('/api/settings');$('setl').innerHTML=Object.entries(s).map(([k,v])=>'<div class=item><b>'+esc(k)+'</b><br><input value="'+esc(v)+'" onchange="setv(\''+esc(k)+'\',this.value)" style="width:100%;box-sizing:border-box"></div>').join('')}}
async function setv(k,v){await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:k,value:v})})}
async function ingest(){let t=$('kt').value.trim();if(t)await api('/api/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:t,source:'web-ui'})});$('kt').value='';load('knowledge')}
api('/api/voice/status').then(x=>{$('voiceStatus').textContent='Vosk '+(x.stt.installed&&x.stt.model_exists?'ready':'not configured')+' • Piper '+(x.tts.voice_exists?'ready':'not configured')}).catch(()=>{$('voiceStatus').textContent='Voice status unavailable.'});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(b.dataset.p).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');load(b.dataset.p)});
loadConvs();selectConv(cid);api('/api/health').then(x=>$('status').textContent=x.model_reachable?' • online':' • offline').catch(()=>{});loadMemory();
</script></body></html>"""
